namaMahasiswa: "Budi"
namaMahasiswa2: "Budi"
nilaiMahasiswa: 90
ipkMahasiswa: 3.5
epochs: 100
batch_size: 32

mahasiswa:
  nama: Budi
  umur: 20
  mkFavorit: [Python, SAP, ABAP, ODOO, 23, "23"]